// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbHj2IzYorPzHXKR1ofV007AL4hI2Slh0',
    appId: '1:745897406662:web:04de709daf725154c2a7c7',
    messagingSenderId: '745897406662',
    projectId: 'app-todo-ff8f2',
    authDomain: 'app-todo-ff8f2.firebaseapp.com',
    storageBucket: 'app-todo-ff8f2.appspot.com',
    measurementId: 'G-VCSFBF6WLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpPS4_AEY60GPaaEX6gACtg7bf4fb8fg',
    appId: '1:745897406662:android:8d38c866b33f06ebc2a7c7',
    messagingSenderId: '745897406662',
    projectId: 'app-todo-ff8f2',
    storageBucket: 'app-todo-ff8f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm3zxNlbOD8MFOb-2u9NdTJz1U3T2Ck4M',
    appId: '1:745897406662:ios:9c33fb0721c0238dc2a7c7',
    messagingSenderId: '745897406662',
    projectId: 'app-todo-ff8f2',
    storageBucket: 'app-todo-ff8f2.appspot.com',
    iosClientId: '745897406662-3scuq0akjlbpuffm6648jlfmpk0goki1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm3zxNlbOD8MFOb-2u9NdTJz1U3T2Ck4M',
    appId: '1:745897406662:ios:9c33fb0721c0238dc2a7c7',
    messagingSenderId: '745897406662',
    projectId: 'app-todo-ff8f2',
    storageBucket: 'app-todo-ff8f2.appspot.com',
    iosClientId: '745897406662-3scuq0akjlbpuffm6648jlfmpk0goki1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
